# Generated by Django 5.1.2 on 2026-02-26 09:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('requires_reason', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('father_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Only numeric digits are allowed.', regex='^\\d+$')])),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('department', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_shamsi', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Date must be in Shamsi format YYYY-MM-DD.', regex='^\\d{4}-\\d{2}-\\d{2}$')])),
                ('month_shamsi', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Month must be in Shamsi format YYYY-MM.', regex='^\\d{4}-\\d{2}$')])),
                ('paid_by', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='core.expensecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Only numeric digits are allowed.', regex='^\\d+$')])),
                ('name', models.CharField(max_length=120)),
                ('father_name', models.CharField(max_length=120)),
                ('grandfather_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Only numeric digits are allowed.', regex='^\\d+$')])),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('transport_fee', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('uniform_fee', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('book_fee', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='core_studen_name_a58b91_idx'), models.Index(fields=['father_name'], name='core_studen_father__bcfad2_idx'), models.Index(fields=['grandfather_name'], name='core_studen_grandfa_c28f83_idx'), models.Index(fields=['phone'], name='core_studen_phone_d6a640_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_shamsi', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Date must be in Shamsi format YYYY-MM-DD.', regex='^\\d{4}-\\d{2}-\\d{2}$')])),
                ('month_shamsi', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Month must be in Shamsi format YYYY-MM.', regex='^\\d{4}-\\d{2}$')])),
                ('other_reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.feetype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.student')),
            ],
        ),
    ]
