# Generated by Django 5.1.2 on 2026-02-26 10:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('year_shamsi', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Year must be YYYY.', regex='^\\d{4}$')])),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('transport_fee', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('uniform_fee', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('book_fee', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='core_school_name_9238d0_idx'), models.Index(fields=['year_shamsi'], name='core_school_year_sh_5b920e_idx')],
                'unique_together': {('name', 'year_shamsi')},
            },
        ),
        migrations.AddField(
            model_name='student',
            name='school_class',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='students',
                to='core.schoolclass',
            ),
        ),
    ]
