# Generated by Django 5.1.2 on 2026-02-26 10:12

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_schoolclass_student_school_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='month_shamsi',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='month_shamsi',
        ),
        migrations.AlterField(
            model_name='expense',
            name='date_shamsi',
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_shamsi',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
