# Generated by Django 5.1.2 on 2026-02-26 10:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_expense_month_shamsi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='bill_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='book_fee',
        ),
        migrations.RemoveField(
            model_name='student',
            name='monthly_fee',
        ),
        migrations.RemoveField(
            model_name='student',
            name='transport_fee',
        ),
        migrations.RemoveField(
            model_name='student',
            name='uniform_fee',
        ),
        migrations.AddField(
            model_name='payment',
            name='bill_number',
            field=models.CharField(default=2435464523, max_length=30, validators=[django.core.validators.RegexValidator(message='Only numeric digits are allowed.', regex='^\\d+$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='month_shamsi',
            field=models.CharField(default=543535636, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.schoolclass'),
        ),
    ]
