# Generated by Django 5.1.2 on 2026-03-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_student_book_fee_override_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="registration_number",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["registration_number"], name="core_studen_registr_c4f725_idx"
            ),
        ),
    ]
