# Generated by Django 5.1.2 on 2026-03-23 00:00

import django.core.validators
from django.db import migrations, models


def fill_unique_registration_numbers(apps, schema_editor):
    Student = apps.get_model("core", "Student")
    seen = set()
    counter = 1
    for student in Student.objects.all().order_by("id"):
        current = (student.registration_number or "").strip()
        if current and current not in seen:
            seen.add(current)
            continue
        # Assign deterministic unique fallback for existing blank/duplicate rows.
        while True:
            candidate = f"AUTO-{counter:06d}"
            counter += 1
            if candidate not in seen:
                break
        student.registration_number = candidate
        student.save(update_fields=["registration_number"])
        seen.add(candidate)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_student_registration_number_and_more"),
    ]

    operations = [
        migrations.RunPython(fill_unique_registration_numbers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="payment",
            name="bill_number",
            field=models.CharField(
                blank=True,
                default="",
                max_length=30,
                validators=[django.core.validators.RegexValidator(message="Only numeric digits are allowed.", regex="^\\d+$")],
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="registration_number",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
