# Generated by Django 6.0.5 on 2026-06-23 08:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_student_registration_unique_and_payment_bill_optional"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherSalaryPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("date_shamsi", django_jalali.db.models.jDateField()),
                ("month_shamsi", models.CharField(blank=True, max_length=7)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_payments",
                        to="core.teacher",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_shamsi", "-id"],
                "indexes": [
                    models.Index(
                        fields=["teacher"], name="core_teache_teacher_e369d3_idx"
                    ),
                    models.Index(
                        fields=["month_shamsi"], name="core_teache_month_s_56c012_idx"
                    ),
                ],
            },
        ),
    ]
